#!/usr/bin/env python3
"""Generate the hardware-suite primary bundle.

The normal clean system-UI bundle is extended with one family-A background.
Keeping both families in one slot-zero bundle lets the suite exercise the
resident family-A and family-B renderers without replacing global bundle state.
All pixels and palettes are generated by the clean-room asset tools.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
ASSET_TOOLS = ROOT / "tools" / "assets"
sys.path.insert(0, str(ASSET_TOOLS))

import build_family_a_background_bundle as family_a  # noqa: E402
import build_system_ui_bundle as system_ui  # noqa: E402
from build_standard_settings_bundle import (  # noqa: E402
    HEADER_WORDS,
    PRIMARY_TAG,
    c_words,
    rgb555,
    words_to_bytes,
)


def set_u32(words: list[int], offset: int, value: int) -> None:
    words[offset] = value & 0xFFFF
    words[offset + 1] = (value >> 16) & 0xFFFF


def build_resources() -> tuple[list[int], list[int], dict[str, int]]:
    bundle, primary, _ = system_ui.build_resources()
    a_bundle, a_primary, a_manifest = family_a.build_resources()

    # Family-A backgrounds use palette selector zero. Keep it visibly patterned
    # but dark enough that a retained frame works as a readable menu backdrop.
    # Family-B sprites and the dynamic font continue using the odd palette.
    primary[0:4] = [
        rgb555(0, 0, 0),
        rgb555(1, 2, 4),
        rgb555(2, 4, 8),
        rgb555(4, 8, 12),
    ]

    # The family-A source has two 0x200-word palette windows. Slot zero already
    # supplies compatible clean palettes, so append only its tilemap/graphics.
    a_payload_start = 0x400
    primary_base = len(primary)
    primary.extend(a_primary[a_payload_start:])

    descriptor_offset = len(bundle)
    image_offset = descriptor_offset + 10
    runtime_offset = image_offset + 18
    auto_offset = runtime_offset + 2

    # The standalone family-A graph has descriptor/image at words 32/46.
    descriptor = list(a_bundle[32:42])
    image = list(a_bundle[46:64])
    set_u32(descriptor, 8, image_offset - HEADER_WORDS)

    old_tilemap = int(str(a_manifest["image"]["tilemap_primary_word_offset"]), 16)
    old_graphics = int(str(a_manifest["image"]["graphics_primary_word_offset"]), 16)
    new_tilemap = primary_base + old_tilemap - a_payload_start
    new_graphics = primary_base + old_graphics - a_payload_start
    set_u32(image, 10, PRIMARY_TAG + new_graphics)
    set_u32(image, 12, PRIMARY_TAG + new_tilemap)
    image[14] = 0
    set_u32(image, 16, runtime_offset - HEADER_WORDS)

    bundle.extend(descriptor)
    bundle.extend(image)
    bundle.extend((0, 0))

    # A+B now has three descriptors. Point at a fresh marker/handle table sized
    # as 2*N marker words followed by 2*N handle words.
    bundle.extend([0] * 12)
    set_u32(bundle, 0x10, descriptor_offset - HEADER_WORDS)
    bundle[0x12] = 1
    set_u32(bundle, 0x14, descriptor_offset - HEADER_WORDS)
    set_u32(bundle, 0x1A, auto_offset - HEADER_WORDS)

    return bundle, primary, {
        "bundle_words": len(bundle),
        "primary_words": len(primary),
        "family_a_descriptor": 0,
        "family_b_settings_descriptor": 0,
        "family_b_poweroff_descriptor": 1,
    }


def write_outputs(output: Path) -> None:
    bundle, primary, manifest = build_resources()
    output.mkdir(parents=True, exist_ok=True)
    system_ui.write_c_output(output, "hw_primary", bundle, primary)

    header_path = output / "hw_primary_resources.h"
    header = header_path.read_text(encoding="ascii")
    header = header.replace(
        "#endif\n",
        "enum { HW_PRIMARY_BACKGROUND_DESCRIPTOR = 0 };\n"
        "mg_sdk_ui_handle hw_primary_create_background(void);\n\n"
        "#endif\n",
    )
    header_path.write_text(header, encoding="ascii")

    source_path = output / "hw_primary_resources.c"
    with source_path.open("a", encoding="ascii") as source:
        source.write(
            "\nmg_sdk_ui_handle hw_primary_create_background(void)\n"
            "{\n"
            "    return mg_sdk_ui_a_create(\n"
            "        HW_PRIMARY_BACKGROUND_DESCRIPTOR);\n"
            "}\n"
        )

    (output / "bundle.bin").write_bytes(words_to_bytes(bundle))
    (output / "primary.bin").write_bytes(words_to_bytes(primary))
    (output / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    write_outputs(args.output.resolve())
    print(f"PASS hardware primary output={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
