def ghidraInstallDir = System.env.GHIDRA_INSTALL_DIR
if (!ghidraInstallDir && project.hasProperty("GHIDRA_INSTALL_DIR")) {
	ghidraInstallDir = project.getProperty("GHIDRA_INSTALL_DIR")
}
if (!ghidraInstallDir) {
	throw new GradleException("GHIDRA_INSTALL_DIR is not defined")
}
apply from: new File(ghidraInstallDir).getCanonicalPath() + "/support/buildExtension.gradle"
