#include "mobigo_sdk/standard_controls.h"

#include "mobigo_sdk/hardware.h"
#include "mobigo_sdk/memory_map.h"
#include "mobigo_sdk/resident_backend.h"

typedef char mg_sdk_standard_controls_must_fit_default_arena[
    sizeof(struct mg_sdk_standard_controls) <=
        MG_SDK_DEFAULT_STANDARD_CONTROLS_RESERVED_WORDS
        ? 1
        : -1];

/* Generated by tools/assets/build_system_ui_bundle.py and linked only for the
 * normal system-UI build profile.  Keeping the adapter here lets applications
 * use one stable SDK header instead of depending on a generated header. */
void mobigo_clean_system_ui_copy_bundle(unsigned short *destination);
void mobigo_clean_system_ui_register(unsigned short *writable_bundle);
mg_sdk_ui_handle mobigo_clean_system_ui_create_settings(void);
mg_sdk_ui_handle mobigo_clean_system_ui_create_poweroff(void);
void mobigo_clean_system_ui_show_brightness(
    mg_sdk_ui_handle handle, unsigned short level);
void mobigo_clean_system_ui_show_volume(
    mg_sdk_ui_handle handle, unsigned short level);
void mobigo_clean_system_ui_hide_settings(mg_sdk_ui_handle handle);
void mobigo_clean_system_ui_show_poweroff(mg_sdk_ui_handle handle);
void mobigo_clean_system_ui_hide_poweroff(mg_sdk_ui_handle handle);

static const struct mg_sdk_system_backend *standard_resident(void)
{
    return &mg_sdk_experimental_resident_backend;
}

static int standard_key_pressed_edge(void *user, mg_sdk_u16 mask)
{
    struct mg_sdk_standard_controls *controls =
        (struct mg_sdk_standard_controls *)user;
    const struct mg_sdk_system_backend *resident = standard_resident();
    int pressed;
    if (resident->key_pressed_edge == 0) {
        return 0;
    }
    pressed = resident->key_pressed_edge(0, mask);
    if (pressed != 0) {
        controls->last_key = mask;
    }
    return pressed;
}

static int standard_load_volume(void *user, mg_sdk_u16 *level)
{
    const struct mg_sdk_system_backend *resident = standard_resident();
    (void)user;
    if (resident->load_volume == 0) return 0;
    return resident->load_volume(0, level);
}

static void standard_save_volume(void *user, mg_sdk_u16 level)
{
    const struct mg_sdk_system_backend *resident = standard_resident();
    (void)user;
    if (resident->save_volume != 0) {
        resident->save_volume(0, level);
    }
}

static void standard_apply_master_gain(void *user, mg_sdk_u16 gain)
{
    const struct mg_sdk_system_backend *resident = standard_resident();
    (void)user;
    if (resident->apply_master_gain != 0) {
        resident->apply_master_gain(0, gain);
    }
}

static int standard_load_brightness(void *user, mg_sdk_u16 *level)
{
    const struct mg_sdk_system_backend *resident = standard_resident();
    (void)user;
    if (resident->load_brightness == 0) return 0;
    return resident->load_brightness(0, level);
}

static void standard_save_brightness(void *user, mg_sdk_u16 level)
{
    const struct mg_sdk_system_backend *resident = standard_resident();
    (void)user;
    if (resident->save_brightness != 0) {
        resident->save_brightness(0, level);
    }
}

static void standard_apply_backlight(void *user, mg_sdk_u16 value)
{
    const struct mg_sdk_system_backend *resident = standard_resident();
    (void)user;
    if (resident->apply_backlight != 0) {
        resident->apply_backlight(0, value);
    }
}

static mg_sdk_u32 standard_ticks(void *user)
{
    const struct mg_sdk_system_backend *resident = standard_resident();
    (void)user;
    if (resident->ticks == 0) return 0;
    return resident->ticks(0);
}

static void standard_show_overlay(
    void *user,
    enum mg_sdk_overlay_kind kind,
    mg_sdk_u16 level,
    mg_sdk_u16 x,
    mg_sdk_u16 y)
{
    struct mg_sdk_standard_controls *controls =
        (struct mg_sdk_standard_controls *)user;
    (void)x;
    (void)y;
    if (kind == MG_SDK_OVERLAY_BRIGHTNESS) {
        mobigo_clean_system_ui_show_brightness(
            controls->settings_handle, level);
    } else if (kind == MG_SDK_OVERLAY_VOLUME) {
        mobigo_clean_system_ui_show_volume(controls->settings_handle, level);
    } else if (kind == MG_SDK_OVERLAY_POWEROFF) {
        mobigo_clean_system_ui_show_poweroff(controls->poweroff_handle);
    }
}

static void standard_hide_overlay(void *user)
{
    struct mg_sdk_standard_controls *controls =
        (struct mg_sdk_standard_controls *)user;
    mobigo_clean_system_ui_hide_settings(controls->settings_handle);
}

static void standard_request_poweroff(void *user)
{
    const struct mg_sdk_system_backend *resident = standard_resident();
    (void)user;
    if (resident->request_poweroff != 0) {
        resident->request_poweroff(0);
    }
}

static const struct mg_sdk_system_backend standard_backend = {
    standard_key_pressed_edge,
    standard_load_volume,
    standard_save_volume,
    standard_apply_master_gain,
    standard_load_brightness,
    standard_save_brightness,
    standard_apply_backlight,
    standard_ticks,
    standard_show_overlay,
    standard_hide_overlay,
    0,
    0,
    standard_request_poweroff
};

int mg_sdk_standard_controls_init(
    struct mg_sdk_standard_controls *controls,
    mg_sdk_u16 *bundle_ram)
{
    if (controls == 0 || bundle_ram == 0) {
        return 0;
    }
    controls->initialized = 0;
    controls->last_key = 0;
    controls->settings_handle = MG_SDK_INVALID_UI_HANDLE;
    controls->poweroff_handle = MG_SDK_INVALID_UI_HANDLE;

    mobigo_clean_system_ui_copy_bundle(bundle_ram);
    mobigo_clean_system_ui_register(bundle_ram);
    controls->settings_handle = mobigo_clean_system_ui_create_settings();
    controls->poweroff_handle = mobigo_clean_system_ui_create_poweroff();
    if (controls->settings_handle == MG_SDK_INVALID_UI_HANDLE ||
        controls->poweroff_handle == MG_SDK_INVALID_UI_HANDLE) {
        if (controls->settings_handle != MG_SDK_INVALID_UI_HANDLE) {
            mg_sdk_ui_b_destroy(controls->settings_handle);
        }
        if (controls->poweroff_handle != MG_SDK_INVALID_UI_HANDLE) {
            mg_sdk_ui_b_destroy(controls->poweroff_handle);
        }
        controls->settings_handle = MG_SDK_INVALID_UI_HANDLE;
        controls->poweroff_handle = MG_SDK_INVALID_UI_HANDLE;
        return 0;
    }

    /* Family-B objects are live immediately after creation.  Hide both clean
     * UI objects before the first application frame so an idle starter does
     * not expose unprepared sprite records at the top-left of the display. */
    mobigo_clean_system_ui_hide_settings(controls->settings_handle);
    mobigo_clean_system_ui_hide_poweroff(controls->poweroff_handle);

    mg_sdk_system_controls_init(
        &controls->policy, &standard_backend, controls);
    controls->initialized = 1;
    return 1;
}

void mg_sdk_standard_controls_poll(
    struct mg_sdk_standard_controls *controls)
{
    if (controls == 0 || controls->initialized == 0) {
        return;
    }
    mg_sdk_system_controls_poll(&controls->policy);
    mg_sdk_watchdog_kick();
}

void mg_sdk_standard_controls_hide(
    struct mg_sdk_standard_controls *controls)
{
    if (controls == 0 || controls->initialized == 0) {
        return;
    }
    mg_sdk_system_controls_hide(&controls->policy);
    mobigo_clean_system_ui_hide_poweroff(controls->poweroff_handle);
}
